<?php

namespace DistrinetBackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TownsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TownsRepository extends EntityRepository
{
}
